USE MASTER
GO

DROP DATABASE IF EXISTS ReviewscoresDB;
GO

CREATE DATABASE ReviewscoresDB;
GO

USE ReviewscoresDB;
GO

CREATE TABLE dbo.[Reviews] (
	[ReviewID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[AuthorID] UNIQUEIDENTIFIER NOT NULL,
	[MovieID] UNIQUEIDENTIFIER NULL,
	[ShowID] UNIQUEIDENTIFIER NULL,
	[ShowEpisodeID] UNIQUEIDENTIFIER NULL,
	[ReviewText] NVARCHAR(MAX) NOT NULL,
	[AuthorRating] DECIMAL NULL
)
GO

CREATE TABLE dbo.[Author] (
	[AuthorID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[AuthorFirstName] NVARCHAR(50) NOT NULL,
	[AuthorLastName] NVARCHAR(50) NOT NULL,
	[AuthorEmail] NVARCHAR(90) NULL
)
GO

CREATE TABLE dbo.[Movie] (
	[MovieName] NVARCHAR(90) NOT NULL,
	[MovieID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Summary] NVARCHAR(MAX) NULL,
	[Length] INT NULL,
	[OfficialRatingID] UNIQUEIDENTIFIER NOT NULL,
	[Studio] NCHAR(50) NULL,
	[Genre] NCHAR(50) NULL,
	[Director] NCHAR(50) NULL,
	[StaringActors] NCHAR(50) NULL,
	[AgeRestriction] NVARCHAR(10) NULL,
	[RegionID] UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE dbo.[TVShow] (
	[ShowID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[ShowName] NVARCHAR(90) NOT NULL,
	[EpisodeLength] NCHAR(10) NULL,
	[Producer] NCHAR(50) NULL,
	[OfficialRatingID] UNIQUEIDENTIFIER NOT NULL,
	[AgeRestriction] NVARCHAR(10) NULL,
	[ShowSummary] NVARCHAR(MAX) NULL,
	[ShowGenre] NVARCHAR(50),
	[EpisodeCount] INT NULL,
	[EpisodeID] UNIQUEIDENTIFIER NOT NULL,
	[RegionID] UNIQUEIDENTIFIER NOT NULL
)
GO

CREATE TABLE dbo.[Episode] (
	[EpisodeID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[ShowID] UNIQUEIDENTIFIER NOT NULL,
	[EpisodeNumber] INT NULL,
	[EpisodeLength] INT NULL,
	[EpisodeName] NVARCHAR(50) NULL,
	[EpisodeDescription] NVARCHAR(MAX) NULL
)
GO

CREATE TABLE dbo.[Region] (
	[RegionID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[RegionName] NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE dbo.[Rating] (
	[OfficialRatingID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[IMDBRating] DECIMAL NULL,
	[BoxOfficeRating] DECIMAL NULL,
	[RottenTomatoesRating] DECIMAL NULL,
	[MetaCriticRating] DECIMAL NULL,
	[AlgorithmRating] DECIMAL NULL,
	[ReviewerRating] DECIMAL NULL
)
GO